"""Write src/components/logo-trail.ts from geometry.json's trail_from_swash.

logo-trail.ts used to be updated by hand after every run of derive_trail.py, and it
drifted: its mask numbers were a run behind the geometry.  The prose belongs with the
data, so it lives here and the whole file is emitted.

    python design/logo-animation/derive_trail.py && python design/logo-animation/emit_trail_ts.py
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
G = json.load(open(HERE / 'geometry.json'))['trail_from_swash']
W, M, K = G['width_joined_path'], G['mask'], G['marks']

lead_in = ' '.join(f'{v:.0f}' for v in M['lead_in_point'])
lead_out = ' '.join(f'{v:.0f}' for v in M['lead_out_point'])

out = f'''// The pen trail: the white swash under the AO mark in the Illustrator source
// (AO.ai page 1), which is what makes the mark one continuous gesture — right
// leg -> trail -> bar.
//
// GENERATED by design/logo-animation/emit_trail_ts.py from geometry.json's
// `trail_from_swash`. Do not edit by hand; re-run derive_trail.py then the
// emitter. These are the `*_joined_d` forms, whose last half is rebuilt
// curvature-continuously so the pen arrives tangent to the bar's left hook,
// whose tail is cut straight on that hook's face, and whose head is held on
// the authored outline over the first {100*G['join']['hold_foot'][1]:.0f}% so the A's foot
// join is the artwork itself (see the `join` block there).
//
// Site path units (tenths, y-up): draw inside
//   <g transform="translate(0,1084) scale(0.1,-0.1)">
// like logo-mark.ts. Both run in the pen's direction: from the A's right foot
// cut midpoint (where the right leg's centre-line ends) to the left hook tip
// (where the bar's centre-line begins).

/** The swash outline, filled. Arc length of its centre-line {G['arc_length_path']:.0f} units;
 *  it is {W['at_foot']:.0f} wide at the foot, {W['max']:.0f} at its widest through the loop and {W['at_left_end']:.0f}
 *  where it meets the hook. */
export const TRAIL_OUTLINE_D =
  '{G['outline_joined_d']}';

/** The swash centre-line: the sweep path for the reveal, and the trail itself
 *  when the component is asked for the plain stroke rendering. */
export const TRAIL_CENTRE_D =
  '{G['centre_joined_d']}';

/** The reveal mask's path: the centre-line with a lead-in and a lead-out, so a
 *  BUTT cap never has to cut across an end face. Stroke it {M['stroke_path']:.0f} wide with
 *  butt caps and dash it with pathLength="1". */
export const TRAIL_MASK_D = `M{lead_in} L${{TRAIL_CENTRE_D.slice(1)}} L{lead_out}`;

/** Where the trail sits on that mask path: a point at fraction f of the TRAIL
 *  is at start + span * f of the mask. */
export const TRAIL_MASK = {{ start: {M['start_fraction']:.4f}, span: {M['span_fraction']:.4f}, strokeWidth: {M['stroke_path']:.0f} }} as const;

/** Landmarks in fractions of the trail, measured on the swash: where the
 *  gesture crosses the A's legs. The choreography is authored against these. */
export const TRAIL_MARKS = {{
  crossesRightLeg: [{', '.join(f'{v:.3f}' for v in K['crosses_right_leg'])}],
  crossesLeftLeg: [{', '.join(f'{v:.3f}' for v in K['crosses_left_leg'])}],
}} as const;
'''
p = HERE.parents[1] / 'src' / 'components' / 'logo-trail.ts'
p.write_text(out, encoding='utf-8')
print(f"  wrote {p.relative_to(HERE.parents[1])}: outline {len(G['outline_joined_d'])} chars, "
      f"mask stroke {M['stroke_path']:.0f}, span [{M['start_fraction']:.4f}, {M['end_fraction']:.4f}]")
