#!/usr/bin/env node
// Export publish:true notes from an Obsidian vault into a small standalone
// repo that CI can check out.
//
// The vault itself never leaves your machine. Only notes explicitly marked
// `publish: true` — plus the attachments they reference — are copied into the
// export repo, so a leak of that repo exposes nothing beyond what is already
// destined for the website.
//
//   VAULT_PATH   source vault (required)
//   EXPORT_PATH  local clone of the export repo (required)
//
//   node scripts/export-vault.mjs           # write files, leave git alone
//   node scripts/export-vault.mjs --push    # also commit and push

import { readFile, writeFile, mkdir, readdir, copyFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, basename, resolve, relative } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import matter from 'gray-matter';

const run = promisify(execFile);

const VAULT_PATH = process.env.VAULT_PATH && resolve(process.env.VAULT_PATH);
const EXPORT_PATH = process.env.EXPORT_PATH && resolve(process.env.EXPORT_PATH);
const SHOULD_PUSH = process.argv.includes('--push');

const IMAGE_EXT = /\.(png|jpe?g|gif|webp|svg|avif)$/i;

function fail(msg) {
  console.error(`✘ ${msg}`);
  process.exit(1);
}

if (!VAULT_PATH) fail('VAULT_PATH is not set');
if (!EXPORT_PATH) fail('EXPORT_PATH is not set');
if (!existsSync(VAULT_PATH)) fail(`Vault not found: ${VAULT_PATH}`);
if (!existsSync(EXPORT_PATH)) fail(`Export repo not found: ${EXPORT_PATH}`);
if (!existsSync(join(EXPORT_PATH, '.git'))) {
  fail(`Export path is not a git repo: ${EXPORT_PATH}`);
}

// Guard against pointing the export at the vault itself, which would delete notes.
const rel = relative(VAULT_PATH, EXPORT_PATH);
if (rel === '' || (!rel.startsWith('..') && !resolve(rel).startsWith('/'))) {
  fail('EXPORT_PATH must not be inside VAULT_PATH');
}

async function walk(dir, predicate) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(path, predicate)));
    else if (entry.isFile() && predicate(entry.name)) out.push(path);
  }
  return out;
}

console.log(`◆ Vault:  ${VAULT_PATH}`);
console.log(`◆ Export: ${EXPORT_PATH}`);

const mdPaths = await walk(VAULT_PATH, (n) => n.endsWith('.md'));
const imagePaths = await walk(VAULT_PATH, (n) => IMAGE_EXT.test(n));
const imageByBasename = new Map();
for (const p of imagePaths) imageByBasename.set(basename(p), p);

const published = [];
for (const path of mdPaths) {
  const raw = await readFile(path, 'utf8');
  let data;
  try {
    ({ data } = matter(raw));
  } catch (err) {
    console.warn(`  ⚠ unparseable frontmatter, skipping: ${basename(path)}`);
    continue;
  }
  if (data.publish === true) published.push({ path, raw, data });
}

if (published.length === 0) {
  fail('No notes marked `publish: true` were found — refusing to empty the export repo');
}

// Attachments referenced by published notes only.
const wanted = new Set();
for (const note of published) {
  for (const m of note.raw.matchAll(/!\[\[([^\]|]+)(?:\|[^\]]*)?\]\]/g)) {
    const target = basename(m[1].trim());
    if (IMAGE_EXT.test(target)) wanted.add(target);
  }
}

// Clear previous export (tracked content only — never touch .git).
for (const entry of await readdir(EXPORT_PATH, { withFileTypes: true })) {
  if (entry.name === '.git') continue;
  await rm(join(EXPORT_PATH, entry.name), { recursive: true, force: true });
}

for (const note of published) {
  await writeFile(join(EXPORT_PATH, basename(note.path)), note.raw);
}

let copied = 0;
let missing = 0;
if (wanted.size) {
  const attachDir = join(EXPORT_PATH, 'attachments');
  await mkdir(attachDir, { recursive: true });
  for (const name of wanted) {
    const src = imageByBasename.get(name);
    if (!src) {
      console.warn(`  ⚠ attachment not found in vault: ${name}`);
      missing++;
      continue;
    }
    await copyFile(src, join(attachDir, name));
    copied++;
  }
}

await writeFile(
  join(EXPORT_PATH, 'README.md'),
  [
    '# Blog vault export',
    '',
    'Generated by `scripts/export-vault.mjs` in the portfolio repo.',
    'Do not edit by hand — changes here are overwritten on the next export.',
    '',
    'Contains only notes marked `publish: true`, and the images they embed.',
    '',
  ].join('\n')
);

console.log(`✓ Exported ${published.length} note(s), ${copied} attachment(s)${missing ? `, ${missing} missing` : ''}`);

if (!SHOULD_PUSH) {
  console.log('  (dry run — pass --push to commit and push)');
  process.exit(0);
}

const git = (...args) => run('git', ['-C', EXPORT_PATH, ...args]);

const { stdout: status } = await git('status', '--porcelain');
if (!status.trim()) {
  console.log('✓ No changes to push');
  process.exit(0);
}

await git('add', '-A');
const stamp = new Date().toISOString().replace('T', ' ').slice(0, 16);
await git('commit', '-m', `content: export ${published.length} published note(s) — ${stamp}`);
await git('push');
console.log('✓ Pushed to export repo');
